version: "3"

services:
  server1:
    image: registry.gitlab.com/qio/custom/126765/flaskapi
    container_name: server1
    environment:
      - SERVER=SERVER1
    ports:
      - "8081:8080"

  server2:
    image: registry.gitlab.com/qio/custom/126765/flaskapi
    container_name: server2
    environment:
      - SERVER=SERVER2
    ports:
      - "8082:8080"

  server3:
    image: registry.gitlab.com/qio/custom/126765/flaskapi
    container_name: server3
    environment:
      - SERVER=SERVER3
    ports:
      - "8083:8080"

  server4:
    image: registry.gitlab.com/qio/custom/126765/flaskapi
    container_name: server4
    environment:
      - SERVER=SERVER4
    ports:
      - "8084:8080"

  haproxy:
    image: registry.gitlab.com/qio/standard/haproxy:2.5
    container_name: haproxy
    ports:
      - "80:80"
    volumes:
      - ${PWD}/data/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

