version: "2"

# Do not forget that the only available 
# redis image is accessible with the following url:
#  registry.gitlab.com/qio/standard/redis:latest

services:
  redis:
    image: registry.gitlab.com/qio/standard/redis:latest
    container_name: redis
    restart: "always"
    mem_limit: 30M
    mem_reservation: 30M
    ports:
      - "6379:6379"
